<?php

namespace Uab\FlorinBundle\Repository;

/**
 * UniversitateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversitateRepository extends \Doctrine\ORM\EntityRepository
{
}
